global:
    epsilon: 0.5
    
    camera: 0
    camera_speed: 1.0
    camera_target: 0

pulse:
    -   name: camera_position
        fps: 30
        type: vector
        shape: |
            function() {
                if (global.camera > global.camera_target + global.epsilon) {
                    global.camera = parseFloat(global.camera) - global.camera_speed;
                    return global.camera;
                }
                else if (global.camera < global.camera_target - global.epsilon) {
                    global.camera = parseFloat(global.camera) + global.camera_speed;
                    return global.camera;
                }
                else {
                    return false;
                }
            }        
        map: [[10.0, -10.0, -10.0], [-10.0, 0.0, -20.0], [-10.0, -10.0, 50.0], [10.0, 0.0, 100.0]]

in:
    OP-Z*:
        -   key: 5-124
            channel: 1
            name: u_kick
            type: number
            map: [0.0, 1.0]

        -   key: 5-124
            channel: 2
            name: u_snare
            type: number
            map: [0.0, 1.0]

        -   key: 5-124
            channel: 3
            name: u_perc
            type: number
            map: [0.0, 1.0]

        -   key: 5-124
            channel: 4
            name: u_sample
            type: number
            map: [0.0, 1.0]
        
        -   key: 5-124
            channel: 5
            name: u_bass
            type: number
            map: [0.0, 1.0]

        -   key: 5-124
            channel: 6
            name: u_lead
            type: number
            map: [0.0, 1.0]

        -   key: 5-124
            channel: 7
            name: u_arp
            type: number
            map: [0.0, 1.0]

        -   key: 5-124
            channel: 8
            name: u_chord
            type: number
            map: [0.0, 1.0]

        -   key: 53-76
            channel: 16
            shape: |
                function() {
                    if (value > 0)
                        global.camera_target = ((parseFloat(key) - 53) / 23) * 127;
                    return false;
                }

out:
    -   csv
    -   osc://localhost:8080
