global:
    epsilon: 0.5
    
    angle: 0
    angle_speed: 1.0
    angle_turn: false
    
    card: 0
    card_max: 30

    background: 0
    background_max: 6

    postprocessing: 0
    postprocessing_max: 2
    
    time: 0.0
    time_status: false

pulse:
    -   name: u_angle
        fps: 60
        type: number
        map: [-6.283, -3.1415, -1.57075, -0.785375, 0.0, 0.0, 0.0, 0.785375, 1.57075, 3.1415, 6.283 ]
        shape: |
            function() {
                if ( global.angle_turn || 
                    (global.angle <= 60 ||
                        global.angle >= 67) )
                    global.angle = parseFloat(global.angle) + parseFloat(global.angle_speed);

                if (global.angle > 127.0)
                        global.angle -= 127.0;
                
                return global.angle;
            }

in:
    OP-Z*:
        -   key: 5-124
            channel: 1
            name: u_kick
            type: number
            map: [0.0, 1.0]

        -   key: 5-124
            channel: 2
            name: u_snare
            type: number
            map: [0.0, 1.0]

        -   key: 5-124
            channel: 3
            name: u_perc
            type: number
            map: [0.0, 1.0]

        -   key: 5-124
            channel: 4
            name: u_sample
            type: number
            map: [0.0, 1.0]
        
        -   key: 5-124
            channel: 5
            name: u_bass
            type: number
            map: [0.0, 1.0]

        -   key: 5-124
            channel: 6
            name: u_lead
            type: number
            map: [0.0, 1.0]

        -   key: 5-124
            channel: 7
            name: u_arp
            type: number
            map: [0.0, 1.0]

        -   key: 5-124
            channel: 8
            name: u_chord
            type: number
            map: [0.0, 1.0]

        # -   key: 53-76
        #     channel: 16
        #     shape: |
        #         function() {
        #             if (value > 0)
        #                 global.camera_target = ((parseFloat(key) - 53) / 23) * 127;
        #             return false;
        #         }

        -   key: 53
            channel: 16
            shape: |
                function() {
                    if (value > 0) {
                        global.angle_turn = true;
                        global.angle_speed = 2.5;
                    }
                    else {
                        global.angle_turn = false;
                        global.angle_target = 1.0;
                    }
                    return false;
                }

        -   key: 54
            channel: 16
            name: u_card
            type: number
            shape: |
                function() {
                    if (value == 0)
                        return false;

                    global.card = parseFloat(global.card) + 1.0
                    
                    if (global.card > parseFloat(global.card_max))
                        global.card = 0;

                    return global.card;
                }

        -   key: 55
            channel: 16
            name: u_background
            type: number
            shape: |
                function() {
                    if (value == 0)
                        return false;

                    global.background = parseFloat(global.background) + 1.0
                    
                    if (global.background > parseFloat(global.background_max))
                        global.background = 0;

                    return global.background;
                }

        -   key: 56
            channel: 16
            name: background_rotate
            type: toggle
            map: 
                on: "define,BACKGROUND_ROTATE"
                off: "undefine,BACKGROUND_ROTATE"

        -   key: 57
            channel: 16
            name: background_moveff
            type: toggle
            map: 
                on: "define,BACKGROUND_MOVEFF"
                off: "undefine,BACKGROUND_MOVEFF"

        -   key: 58
            channel: 16
            name: u_postprocessing
            type: number
            shape: |
                function() {
                    if (value == 0)
                        return false;

                    global.postprocessing = parseFloat(global.postprocessing) + 1.0
                    
                    if (global.postprocessing > parseFloat(global.postprocessing_max))
                        global.postprocessing = 0;

                    return global.postprocessing;
                }


        

        -   status: START_SONG
            name: define
            type: state
            map: "OPZ_PLAYING"
            shape: |
                function() {
                    global.time_status = true;
                    global.time = 0.0;
                    return true;
                }

        -   status: STOP_SONG
            name: undefine
            type: state
            map: "OPZ_PLAYING"
            shape: |
                function() {
                    global.time_status = false;
                    return true;
                }

        -   status: TIMING_TICK
            name: u_clock
            shape: |
                function() {
                    if (global.time_status == true) {
                        global.time = parseFloat(global.time) + 0.05;
                        return parseFloat(global.time);
                    }
                    else {
                        return false;
                    }
                }

                -   key: 5-124


            


out:
    -   csv
    -   osc://localhost:8081
